# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Charts'

target 'kantengerusa_Geek12' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kantengerusa_Geek12

end
