# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'

target 'Acceleration_collection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Acceleration_collection

  target 'Acceleration_collectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Acceleration_collectionUITests' do
    # Pods for testing
  end

end
